# Generated by Django 4.1.5 on 2023-02-26 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_trackeddate_habittracker_habit_habit_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='month',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
