# Generated by Django 4.1.5 on 2023-03-28 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_habit_month_habit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='month',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='habittracker',
            name='month',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('user', 'habit_tracker', 'name'), name='unique_user_habit_per_habit_tracker'),
        ),
        migrations.AddConstraint(
            model_name='habittracker',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_habit_tracker'),
        ),
        migrations.AddConstraint(
            model_name='trackeddate',
            constraint=models.UniqueConstraint(fields=('tracked_date', 'habit'), name='unique_tracking_date_for_habit'),
        ),
    ]
