# Generated by Django 4.1.5 on 2023-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_habit_month_alter_habittracker_month_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackeddate',
            name='unique_tracking_date_for_habit',
        ),
        migrations.RenameField(
            model_name='trackeddate',
            old_name='tracked_date',
            new_name='date',
        ),
        migrations.AddConstraint(
            model_name='trackeddate',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique_tracking_date_for_habit'),
        ),
    ]
