# Generated by Django 4.1.5 on 2023-05-03 00:57

from django.db import migrations, models
import habit_tracker.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_alter_habit_month_alter_habit_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.TextField(validators=[habit_tracker.custom_validators.no_empty_strings]),
        ),
    ]
