# Generated by Django 4.1.5 on 2023-05-04 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0007_alter_habit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracker',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Month value must be more than or equals to 1.'), django.core.validators.MaxValueValidator(12, message='Month value must be less than or equals to 12.')]),
        ),
        migrations.AddConstraint(
            model_name='habittracker',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='check_month_min_max_values'),
        ),
    ]
